#!/bin/bash
#SBATCH --job-name=planck12
#SBATCH --partition=gen
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=20
#SBATCH --time=00:45:00

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

module load adri_gcc
module load adri_base

source /mnt/home/aduivenvoorden/.pyenv/versions/enki/bin/activate

TAG=planck12
SCRIPTDIR="/mnt/home/aduivenvoorden/local/optweight/scripts/paper"
BASEDIR="/mnt/home/aduivenvoorden/project/actpol/20230621_pcg_planck/${TAG}"

NITER_CG=5
NITER_MG=20

srun -u --cpu-bind=cores -c$SLURM_CPUS_PER_TASK python ${SCRIPTDIR}/planck_filter_pix.py ${BASEDIR} --niter-cg ${NITER_CG} --niter-mg ${NITER_MG} --lmax-masked-cg 2000 --write-steps

cp slurm-${SLURM_JOB_ID}.out ${BASEDIR}/
