# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-linux:
    name: "Run tests on Linux"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install MKL
      run: |
        sudo apt install intel-mkl

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install pytest
        python -m pip install "Cython<3.0.4"
        python -m pip install numpy 
        python -m pip install scipy
        python -m pip install astropy
        python -m pip install healpy
        python -m pip install matplotlib
        python -m pip install pyyaml
        python -m pip install h5py
        python -m pip install Pillow
        python -m pip install ducc0
        python -m pip install pixell
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build optweight
      run: |
          python -m pip install .
    - name: Test with pytest
      run: |
        cd tests
        pytest -m pytest .
