name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-linux:
    name: "Run tests on Linux"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]	

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install MKL
      run: |
        sudo apt update
        sudo apt install intel-mkl

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install flake8
        python -m pip install pytest
        python -m pip install pytest-cov
        python -m pip install "Cython<3.0.4"
        python -m pip install numpy 
        python -m pip install scipy
        python -m pip install astropy
        python -m pip install healpy
        python -m pip install matplotlib
        python -m pip install pyyaml
        python -m pip install h5py
        python -m pip install Pillow
        python -m pip install ducc0
        python -m pip install pixell
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build optweight
      run: |
          export CPATH=/usr/include/mkl/:$PATH
          export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LIBRARY_PATH
          python -m pip install . -v
    - name: Test with pytest
      run: |
        cd tests
        python -m pytest --cov=optweight --cov-report=xml --cov-report=html .
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
